### ISSUE TITLE
Missing `pandas-ta` optional dependency

### ISSUE THREAD

**Issue by Witiko** [MIR-MU/seqrep#1]
The example Jupyter notebook lacks the `pandas-ta` optional dependency. [Here](https://github.com/iterative/dvc/blob/master/setup.py#L56) is how DVC handles [optional dependencies](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies).

**Comment by JakRys** [comment]
Missing dependency was added to package requirements.
